### PR TITLE
Add Modal component

### LINKED ISSUE #8: Rich modal with custom component
Would you consider adding another modal, that can be open programmatically, where you could pass a component? This would allow to create rich modals (eg. with forms).

### PR DESCRIPTION
**Pull request by korpa**
fixes #8

### CODE REVIEW

**Comment by rodymol123** [comment]
I would love to see this have the same body appending functionality like the dialog has, because it currently is a nightmare with z-index and absolutely positioned containers.

Should be a simple copy and paste trick from the Dialog component, but could save a lot of headaches.
And as always, thanks for being the amazing person you are by contributing to something I like ;)

Example

**Comment by rafaelpimpa** [comment]
Exactly what I thought, making it programatically like Dialog (creating dynamically direct to the body element) would be better.

**Comment by rodymol123** [comment]
Ditching the card for generic elements would make it more in line with the options Bulma set out with the modal, like image modals. And it would allow for the card modals too.

**Comment by rafaelpimpa** [comment]
Yep, the thing is, if you're inject a component, that component would be the card you want. Just have to think about a way to close the modal within the injected component.

**Comment by rodymol123** [comment]
Maybe emit a close event that can be handled by the parent?

**Comment by korpa** [comment]
Hi guys,
the idea was to use slots and that you can define the modal directly were you want use it. But I see the problem. Will give it another try.

@rodymol123 Could you give me the code of the example dashboard your screenshot shows? Then I can test it directly in the use case.

**Comment by rodymol123** [comment]
@korpa Can you run Laravel? If you can't, I will detach it from my Laravel setup for you ;)

**Comment by korpa** [comment]
Yes, Laravel is fine.

**Comment by rodymol123** [comment]
@korpa I sent you an invite to my private repo containing the Laravel project and VueJS app :)

**Comment by rafaelpimpa** [comment]
Closing this because I'm adding it myself, release goes live probably this week.

**Pull request closed without merging**
