### PR TITLE
#284 changeable pagination icons added

### PR DESCRIPTION
**Pull request by moeenzarrinfam**
problem fixed by adding props to **b-table** and **b-pagination**
default values didn't changed

#284 
tnx

### CODE REVIEW

**Comment by jtommy** [comment]
@moeenzarrinfam I think it's a good idea. Please resolve conflicting files.

**Comment by moeenzarrinfam** [comment]
@jtommy resolved

**Comment by jtommy** [comment]
@moeenzarrinfam I'm looking your commit and the problem is about 'both' prop to b-icon component. This prop is used to internal component to manage different pack names with the same icon name. 
Your commit allow to use all 'mdi' icons only and the current equivalent icon (see Icon component source)

**Comment by moeenzarrinfam** [comment]
@jtommy oops!... I didn't know that 
last commit contains my idea to solve the problem .
please check it.
tnx

**Comment by jtommy** [comment]
@moeenzarrinfam I think that it's only a workaround because now there are 'mdi' and 'fa' icon pack but in the future?
You should enable/disable both prop if the current icon is equals to default or not, or another solution but it have to general.

**Comment by jtommy** [comment]
@moeenzarrinfam We thought about this PR and at the end most of the components (panel, table, datepicker, ..) using icons don't allow to change these. So we prefer follow this way, at the moment.
Anyway let me thank you for the support and the spent time :thumbsup:

**Pull request closed without merging**
