### PR TITLE
Dialog: component injection added

### PR DESCRIPTION
**Pull request by korpa**
This is a proposal how to inject a component into dialogs.

### CODE REVIEW

**Comment by rafaelpimpa** [comment]
I'm sorry I didn't see your message before asking in #8, it went unnoticed :(

Would you separate this on a new ``Modal`` component?

It's more of a semantic issue for me, if you're injecting an entire form or anything else for example, it's not a Notice/Dialog anymore, should be treated differently.

Then I'll create a new branch for this so I can clone to see how's it 👍

**Comment by korpa** [comment]
I will look into this. I think it even could be easier to do this as a separate component, as I may can use "vue slots"

**Comment by korpa** [comment]
I reseted my master and therefor the PR is closed. I will open a new one, as soon as I have a new component.

The component injection into dialog can be found here: https://github.com/korpa/buefy/tree/27-component-in-dialog

**Comment by rafaelpimpa** [comment]
Thank you

**Pull request closed without merging**
