### PR TITLE
Add extra slot to data table - allow level-left to be overwritten

### PR DESCRIPTION
**Pull request by tgosp**
Allow this number - http://d.pr/i/Msi7MB to be replaced with action buttons.
Here is how the table will look with action buttons - http://d.pr/i/lcF6uo

Please ping me if I have to do some extra changes here.

### CODE REVIEW

**Comment by tgosp** [comment]
@rafaelpimpa - Please review this when you have time.
Ping @jtommy

**Comment by jtommy** [comment]
@tgosp Thanks. We're updating docs as you can see. We'll review as soon as possible.

**Comment by tgosp** [comment]
Thank you so much @jtommy 

I'm missing few more things around the data component. 
Expect more requests soon.

**Comment by rafaelpimpa** [comment]
Hi @tgosp, thanks for contributing!

We gonna make it a lot simpler, just a simple named slot so the dev can add anything he/she wants, that's why this will be closed, thanks for the original idea!

**Pull request closed without merging**
