### PR TITLE
Add Menu component

### PR DESCRIPTION
**Pull request by tsctao**
#178 

I take some time during you doesn't respond my issue yet to make it. I'm not sure if you like this one.

I make it to support multi-level menu and router-link component. The difficulty is how to manage states across these components, so the data flow is a bit ugly.

Edit: I forgot it, toggle animation is also difficult part. I take a lot of time to make it work every browser and my mobile device. You may review it again to make sure it works.

### CODE REVIEW

**Comment by rafaelpimpa** [comment]
Hey @tsctao I really like it! It's well documented and following the guidelines, thank you very much!

The only thing that is not good is the animation, using height for transitions won't have a good performance, in fact if we change the ``<transition>`` (of MenuDropdown.vue) to ``<transition-group>`` and animate the ``<li>`` instead, [if I'm not mistaken] Vue automatically uses the [FLIP technique](https://aerotwist.com/blog/flip-your-animations/) to animate, could you try that?

Ref: https://vuejs.org/v2/guide/transitions.html#List-Transitions

**Comment by rafaelpimpa** [comment]
I'm gonna wait for you fix before updating the project structure (I'm updating vue-cli and fix the eslint).

**Comment by tsctao** [comment]
After I tried to understand the concept and implement it, I have no idea how to get it works. I need some time rethink it thoroughly. Can you give me more hint?

**Comment by rafaelpimpa** [comment]
OK, I'll accept the PR and make some adjustments, thanks!

**Comment by rafaelpimpa** [comment]
After some testing I couldn't make it work with the FLIP technique, my guess is for that to work we have to have every list item as a transition-group to work properly. I'm just gonna remove the animation to not cause lag/fps drops.

**Comment by tsctao** [comment]
Yeah, I thought I need to wrap them all with `transition-group` but I tried it and it doesn't work. Maybe it needs many hacks.

Another way, I will try to apply `translate3d` by calculate the positions manually.

PS. `translate3d` is GPU animation, is it right?

**Comment by rafaelpimpa** [comment]
Didn't see before your question, yep all ``transforms`` properties, ``opacity`` and ``filter`` are GPU-based.

**Pull request merged**
