### PR TITLE
Updated the customization section.

### PR DESCRIPTION
**Pull request by colsen1991**
Warning the user of a difference from the start section. Ref #306

### CODE REVIEW

**Comment by rafaelpimpa** [comment]
HI @colsen1991 
I'm sorry for the delay, I've updated the docs structure so there's conflicts, if you fix it I can merge! Thanks

**Comment by colsen1991** [comment]
@rafaelpimpa No worries :) We all have lives outside of GitHub, hehe. I'll get to it ASAP 👍

**Comment by colsen1991** [comment]
Should be all good(?)!

**Comment by rafaelpimpa** [comment]
Thanks :)

**Pull request merged**
