### PR TITLE
Add defaultNoticeDuration constructor option.

### PR DESCRIPTION
**Pull request by quimarche**
Ref. https://github.com/rafaelpimpa/buefy/issues/128

### CODE REVIEW

**Comment by quimarche** [comment]
Because of the different props/defaultParam patterns, I've refactored my fix to separate out the two durations.

**Comment by rafaelpimpa** [comment]
That's even better, very appreciated this PR :)

**Comment by jivemonkey2000** [comment]
Hello good folks. This appears to be broken in v0.4.3 - both toast and snackbars are closing instantly on the Buefy site ([toast](https://buefy.github.io/?#/documentation/toast) and [snackbar](https://buefy.github.io/?#/documentation/snackbar)) after updating. Explicitly passing a duration to $toast still works.

**Comment by quimarche** [comment]
Okay, I'll take a look.

**Comment by rafaelpimpa** [comment]
Thanks @quimarche - I forget to test that, my bad 😞

**Pull request merged**
