### PR TITLE
WIP: Tag input component

### PR DESCRIPTION
**Pull request by jgerbes**
A tag input component that allows the user to enter an array of tag strings.

**Completed**
- Basic add and remove functionality.
- `v-model` support.
- Field states (partially complete).
- Tag options (class, size, modifiers).
- Limit number of tags.

**To be done**
- Disabled and loading states.
- Autocomplete.
- Transitions/animation for add and remove.
- Reduce duplicated code from `b-input`.
- Validation.
- Add comments + tidy code.
- Finish documentation.

**Known issues**
- Icon size and alignment.
- Error handling for invalid input (currently just ignores and clears input).

**Other thoughts**
- This component could be incorporated into the b-input component (`type="tags"`) to reduce duplicate code.
- It might be worthwhile making a standalone `b-tag` component.

### CODE REVIEW

**Comment by rafaelpimpa** [comment]
It's looking good @jgerbes!

I like your code very much, plain simple.

One thing I'm not sure is the ``maxlength`` thing, the dev could need to set a maxlength for each tag as well, we might have to separate ``maxlength`` from ``maxtags`` or something.

> This component could be incorporated into the b-input component (type="tags") to reduce duplicate code.

Let's keep separate, otherwise we would have to also merge it to ``b-autocomplete``.

> It might be worthwhile making a standalone b-tag component.

Yep. I'm actually going to do it right now before anything else.

**Comment by rafaelpimpa** [comment]
I've just added a new Tag component: https://github.com/rafaelpimpa/buefy/commit/842aba88491f6fc5ef721ad9b3dcbce69758f725

**Comment by jgerbes** [comment]
Ok, I have updated and implemented the new Tag component.

I also added `maxtag` and `maxlength` props and modified the counter to show the count accordingly (let me know if you have a suggestion on how to do this better).

Also, I made a few changes to the API docs for the Tag component and made the delete button size dynamic.

**Comment by rafaelpimpa** [comment]
Hey @jgerbes your commit is pushing things from past commits I've made, can you fix that? It's harder to review the code.

**Comment by jgerbes** [comment]
Hey @rafaelpimpa could you please explain? I pulled the latest version of `dev` to access the new tag component. Here's a list of changes that I made:

- Added transition to tag component.
- Made tag delete button size dynamic.
- Amended API docs for tag component.
- Updated tag input component to use new tag component.
- Added `maxtag` and `maxlength` props to tag input component.
- Amended docs for tag input component.

**Comment by rafaelpimpa** [comment]
I think it's better to close this and create a new PR then, the way it is isn't intuitive.
Also, I did not added a transition to tag so we can use transition-group inside the tag-input.

Thanks!

**Comment by jgerbes** [comment]
@rafaelpimpa I have sorted out the merge conflicts and will commit the update soon.

**Comment by jgerbes** [comment]
@rafaelpimpa I have pushed the update. Note that I have made a few changes to the `b-tag` component and its docs.

Please give your input about the transitions. I tried using `transition-group` but ran into some issues:

All items within a `transition-group` must have a key. Issue is that the `<input>` is not part of the `v-for`. Assigning a key to the input thats greater than that of the tags (e.g. `tags.length`) works but introduces new issues (glitchy rendering and input loses focus each time `tags` changes).

I think that adding a fade transition to the `b-tag` *may* be the best option as it would also be consistent with the rest of the components (remember that deletable tags may be used elsewhere also).

I have looked into your `b-dropdown` component and feel that it could be broken down into reusable parts (and then reused with the tag input component).

I haven't yet had time to address the known issues or other outstanding tasks. Your input here would be great.

**Comment by rafaelpimpa** [comment]
Hey @jgerbes my bad on the delay, last week I didn't have time to touch buefy, I'll take a look at this during this week.

**Comment by rafaelpimpa** [comment]
@jgerbes I think it's pretty good, I'm ok with your changes on tag. I would like to take from here if you don't mind? To add the autocomplete functionality.

One think to change is the docs, since I've updated its structure, if you update it I could merge and then implement the autocomplete. Also, update only tags docs if you make any changes to it.

Thanks a lot, and sorry for the delay, busy days :D

**Comment by jgerbes** [comment]
@rafaelpimpa I have updated it to reflect the new docs structure. Please note that the changes to the Tag component and docs is intentional.

Please see initial comment for overview of what's remaining to be completed.

**Comment by rafaelpimpa** [comment]
You mind if I accept how it is and finish myself?

**Comment by jgerbes** [comment]
Yeah that’s fine.

**Comment by syropian** [comment]
Looking forward to this! It's exactly what I need :)

**Comment by adrlen** [comment]
Any clues when this PR will be merged ?

Thanks for your work !

**Comment by rafaelpimpa** [comment]
Thanks for your patience people, really busy days.

Since docs updated and I don't want to take any more time from jgerbes, I'll just close this and copy the files that are necessary.

**Pull request closed without merging**
