### PR TITLE
Update Modal onCancel function

### PR DESCRIPTION
**Pull request by gongzza**
when Modal is closed, i want to receive arguments.

### CODE REVIEW

**Comment by gongzza** [comment]
for example
``` js
// ModalForm.vue
this.$emit('close', 'gongzza')

// Parent.vue
this.$modal.open({
  component: ModalForm,
  onCancel: name => {
    this.name = name
  }
})
```
when Modal is closed, `this.name`'s value will be `gongzza`.

**Comment by rafaelpimpa** [comment]
Hi, thanks for contributing!

Does the ``apply`` is needed here? We're not passing another ``this`` 🤔

**Comment by gongzza** [comment]
i'm sorry. i can't understand what you said that "We're not passing another `this`"?

i looked this. so i used `apply`
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator

**Comment by rafaelpimpa** [comment]
Nevermind, you're right.

**Pull request merged**
