### PR TITLE
WIP: Popover component

### PR DESCRIPTION
**Pull request by Tobbe**
PR for #103 

Initial PR just to get more eyes on the code.

I have some tests prepared that are not added yet. Will add those later.
Documentation needs to be written (basic page created)
The popover needs to better respond to page resizes

### CODE REVIEW

**Comment by rafaelpimpa** [comment]
Hey @Tobbe I'm sorry for the delay on this, was fixing a lot of bugs. It's a great addition to buefy for sure!

In general it's great, but there's some bugs left, responsiveness etc. (that ``resize`` method I'm not sure if that is needed, I'm pretty sure it can be done with css only). Are you gonna have time to polish it? Also it's not following the guidelines.

**Comment by rafaelpimpa** [comment]
Actually, after seen the WIP of the dropdown from Bulma, I guess I'll have to remake the dropdown and gonna make it work for popover too.

**Comment by Tobbe** [comment]
Sorry for not answering, I've been on vacation abroad... 
I'd love to do what I can to get this merged. Can I help with the dropdown?

**Comment by rafaelpimpa** [comment]
Hey @Tobbe thanks but it's pretty much done :D
Take a look at the Dropdown, it can be used as Popover now, thanks anyway I got some ideas from your implementation

**Pull request closed without merging**
