### PR TITLE
Use components to add HTML to table columns

### PR DESCRIPTION
**Pull request by korpa**
See #14 
v-html should not be used: https://vuejs.org/v2/guide/syntax.html#Raw-HTML Furthermore components are more flexible in my opinion.

Therefore I changed the table component that you can inject components instead of using the format method to style cells.

@rafaelpimpa I have to clean up a few things e.g. documentation. But before I do this I want to show this to you if you would be happy with this way.

### CODE REVIEW

**Comment by korpa** [comment]
Perfect. I will fix all these points and provide an updated PR.

**Comment by rafaelpimpa** [comment]
Nice :)

Don't forget to update the docs as well, and if you want a sugestion: I would use the Icon component for the docs example, you can generate another json in this site: https://www.mockaroo.com

**Comment by rafaelpimpa** [comment]
Also I just added the [contribution guide](https://github.com/rafaelpimpa/buefy/blob/master/.github/CONTRIBUTING.md)

**Comment by korpa** [comment]
Hi @rafaelpimpa,

I fixed the topics you mentioned + provided a documentation. I added a few sentences regarding the differences plus pros and cons of the renderHtml and the component injection method. I'm not sure, if you like it this way. If not, feel free to update it.

Please let me know if you are willing to accept this PR already or if there are still things you would like to be updated.

Regarding the contribution guide: You ask contributors to use 4 space indention, but your editorconfig file says 2 space indention.

**Pull request merged**
