### PR TITLE
Add Typings for Typescript

### PR DESCRIPTION
**Pull request by mmitchellgarcia**
Resolves Issue #258.

Added typings for
- `Buefy` default export
- Dialog
- LoadingProgrammatic
- ModalProgrammatic
- Snackbar
- Toast

image

### CODE REVIEW

**Comment by mmitchellgarcia** [comment]
@rafaelpimpa hey! I wanted to check that you saw this PR. Let me know if you have any issues or questions on what I did. This is a very valuable feature for Typescript users.

**Comment by rafaelpimpa** [comment]
Hey, sorry for the delay. Did you generate this automatically or do I have to update it by hand whenever I made a change?

**Comment by mmitchellgarcia** [comment]
@rafaelpimpa No problem. You will have to update them by hand.

**Comment by mmitchellgarcia** [comment]
@rafaelpimpa did you get a chance to review this PR? What are your thoughts?

**Comment by rafaelpimpa** [comment]
I'll discuss this with @jtommy but should be ok if you take the responsibility to update it :)

**Comment by mmitchellgarcia** [comment]
@jtommy @rafaelpimpa Hey guys! Did you get the chance to discuss? Thank you.

**Comment by anteriovieira** [comment]
Hi @mmitchellgarcia, I think the package is becoming a little swelling due to the amount of files. What do you think about redirecting the pull request to the  [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository?

**Comment by anneau** [comment]
vuex or vue-router include Typings file in package.
So, I think that this PR may merge....
@rafaelpimpa How about discuss?

**Comment by anteriovieira** [comment]
Can someone list the benefits of having the types incorporated in the package?

**Comment by anneau** [comment]
> the latest TypeScript knows how to resolve type declarations in NPM packages, this means when installed via NPM, you don’t need any additional tooling to use TypeScript with Vue.

From https://vuejs.org/v2/guide/typescript.html#Official-Declaration-in-NPM-Packages

I think that previous typescript cannot resolve type declarations in NPM packages, then people uses DefinitelyTyped.
But latest typescript support to resolve them.
So, we can include typed files in the project.

**Comment by anteriovieira** [comment]
Thanks @anneau . @rafaelpimpa we can merge this pull request.

**Comment by rafaelpimpa** [comment]
Thanks guys for clearing things up

**Pull request merged**
