### PR TITLE
Added datakey prop to table for a key on the table loop

### PR DESCRIPTION
**Pull request by jaybeecave**
Fix for #117

### CODE REVIEW

**Comment by jaybeecave** [comment]
I thought about doing that also... But will it work reliably? I didn't test but in my head they still have the same index?

**Comment by rafaelpimpa** [comment]
It will be unique for each row

**Comment by jaybeecave** [comment]
Can you pass the index through the row props also? its useful to have

**Comment by rafaelpimpa** [comment]
It already does (in the scoped slot)

**Pull request closed without merging**
