### PR TITLE
"Lazy" binding Input component

### PR DESCRIPTION
**Pull request by jtommy**
PR #150

### CODE REVIEW

**Comment by rafaelpimpa** [comment]
Actually that is not a breaking change since already emit on @change 👍 

Thanks!

**Comment by rafaelpimpa** [comment]
I've tested and still doesn't work, look at https://github.com/vuejs/vue/issues/5743

``v-model`` modifiers doesn't work on custom components.

**Comment by jtommy** [comment]
Yes, it's ok. 
"v-mode.lazy" doesn't work on custom component but the equivalent form is <b-input :value="myVar" @change="value => myVar = value" />. The problem was about 'change' event into input method and a lazy solution (value + change) didn't work.

**Comment by rafaelpimpa** [comment]
oh I see, it's fine then 👍

**Pull request merged**
